"""sync runs table schema

Revision ID: 597f7615e8de
Revises: 002
Create Date: 2025-11-06 12:08:25.114622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '597f7615e8de'
down_revision: Union[str, None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_artifacts_project_id'), 'artifacts', ['project_id'], unique=False)
    op.add_column('runs', sa.Column('prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('runs', sa.Column('recalled_memory', sa.JSON(), nullable=True))
    op.add_column('runs', sa.Column('total_cost', sa.Float(), nullable=True))
    op.add_column('runs', sa.Column('token_usage', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs', 'token_usage')
    op.drop_column('runs', 'total_cost')
    op.drop_column('runs', 'recalled_memory')
    op.drop_column('runs', 'prompt')
    op.drop_index(op.f('ix_artifacts_project_id'), table_name='artifacts')
    # ### end Alembic commands ###
