"""agent orchestration pipeline

Revision ID: 04e71c55990d
Revises: add_orchestrations
Create Date: 2025-11-07 10:10:10.375493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '04e71c55990d'
down_revision: Union[str, None] = 'add_orchestrations'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'agents',
        sa.Column(
            'default_model',
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
            server_default='gpt-4o-mini'
        )
    )
    op.add_column('agents', sa.Column('instructions', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    with op.batch_alter_table('orchestrations', schema=None) as batch_op:
        batch_op.alter_column('agent_progress',
                               existing_type=sa.JSON(),
                               nullable=False)
        batch_op.alter_column('agent_outputs',
                               existing_type=sa.JSON(),
                               nullable=False)
        batch_op.alter_column('outputs',
                               existing_type=sa.JSON(),
                               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orchestrations', schema=None) as batch_op:
        batch_op.alter_column('outputs',
                               existing_type=sa.JSON(),
                               nullable=True)
        batch_op.alter_column('agent_outputs',
                               existing_type=sa.JSON(),
                               nullable=True)
        batch_op.alter_column('agent_progress',
                               existing_type=sa.JSON(),
                               nullable=True)
    op.drop_column('agents', 'instructions')
    op.drop_column('agents', 'default_model')
    # ### end Alembic commands ###
